
server:
  port: 8001
  
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: wexplorerdb
      password: root
  application:
    name: UserService
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9091/eureka
